### ISSUE TITLE
Bad performance?

### ISSUE THREAD

**Issue by ecederstrand** [andrewcooke/simple-crypt#8]
While benchmarking unrelated code, I noticed that decrypt() is surprisingly slow (for me, at least). Decrypting a simple encrypted string takes over 3 seconds on a new MacBook Pro. Here's my test:

```python
timeit.timeit("simplecrypt.decrypt('salt', binascii.unhexlify(b'73630002e80f352a44c78bd87d3b0715fed6f8e5b338f066bcd5ddecb4f0e7b5ac96fffff090c6cff365d26c0d80651bc48c3eda7f85828d021d319be2ca11029c08c0b543188517e37168e6'))", setup="import simplecrypt, binascii;", number=10)
```

Is this to be expected?

**Comment by andrewcooke-isti** [comment]
yes, it's expected.  unfortunately it's a side effect of the cryptography.

simple-crypt uses an algorithm called PBKDF2 to process the password you give.  this is to make the security stronger, even for relatively "poor" passwords.

in short, it slows someone down who is trying to guess your password, because they, too, need to spend 3 seconds for each guess.

the trouble with the technique is that it's a compromise.  too "weak" and it doesn't protect much.  too "much" and it takes an annoying long time.  the original simple-crypt used a lower level of security, which was appropriate when it was released a few years ago now.  the latest release increased the level, because computers are getting better. 

so there's nothing i can do (sorry!).  it's just a trade-off necessary for security (i'm surprised it's so long on a new macbook pro, but it's not outside the realms of possibility - the new level is rather conservative).

**Comment by andrewcooke-isti** [comment]
oh, sorry, commented from my work account (waiting on a compile...).  but this is andrewcooke the author.

**Comment by ecederstrand** [comment]
Ok, thanks for the quick reply!

**Comment by SoftwareWarlock** [comment]
I'm hitting a performance issue as well that seems to be more than just a slow algorithm, and I figured this would be the best place to ask. It can take anywhere up to 26 seconds to decrypt on i5-4460 PC, which is just unbearable.

I was thinking it could possibly be a clashing pip package or something like that. Any ideas?

**Comment by andrewcooke** [comment]
is it only decrypt, or both encrypt and decrypt?  the PBKDF reason above affects both.  if only decrypt is slow, but encrypt is fast, then something sounds odd.

if you replace
```
def _pbkdf2(password, salt, n_bytes, count):
    # the form of the prf below is taken from the code for PBKDF2
    return PBKDF2(password, salt, dkLen=n_bytes,
                  count=count, prf=lambda p,s: HMAC.new(p,s,HASH).digest())
```
with
```
def _pbkdf2(password, salt, n_bytes, count):
    print("before pbkdf")
    try:
        # the form of the prf below is taken from the code for PBKDF2
        return PBKDF2(password, salt, dkLen=n_bytes,
                  count=count, prf=lambda p,s: HMAC.new(p,s,HASH).digest())
    finally:
        print("after pbkdf")
```
you will see if the time is in the pbkdf function.

**Comment by SoftwareWarlock** [comment]
It seems that the pbkdf2 implementation is the issue. I just upgraded to the latest version and it seems to be preforming faster now, not sure what was going on. Thanks for your time!
